=== Asim-Tahir/rsc-vs-ssr-with-express/src/server/db/album/data.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "http://example.com/album.schema.json",
  "title": "Albums",
  "type": "array",
  "default": [],
  "items": {
    "title": "Album Item",
    "type": "object",
    "required": [
      "id",
      "artist",
      "title",
      "cover",
      "songs"
    ],
    "properties": {
      "id": {
        "title": "Album id",
        "type": "string",
        "examples": [
          "glass-animals-how-to-be",
          "bjork-post"
        ]
      },
      "artist": {
        "title": "Album artist",
        "type": "string",
        "examples": [
          "Bj√∂rk",
          "Glass Animals"
        ]
      },
      "title": {
        "title": "Album title",
        "type": "string",
        "examples": [
          "Post",
          "How To Be A Human Being"
        ]
      },
      "cover": {
        "title": "Album cover image",
        "type": "string",
        "examples": [
          "https://i.discogs.com/nKIGMO-FhgjIZAxpTKIx__vLsrg6XTEUEbeMXtgnJMs/rs:fit/g:sm/q:90/h:581/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMjQ4/MS0xMjMyMTQ2Nzgy/LmpwZWc.jpeg",
          "https://i.discogs.com/H-kC9IIS7dglokcAXmfrRHji0roeA3SMxrNFr9MtBzQ/rs:fit/g:sm/q:90/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5NTM0/NzAtMTQ3MjE0NTUx/My03NjA2LmpwZWc.jpeg"
        ]
      },
      "likes": {
        "title": "Album like count",
        "type": "integer",
        "examples": [
          21,
          42
        ]
      },
      "songs": {
        "title": "Songs in Album",
        "type": "array",
        "items": {
          "title": "Song",
          "type": "object",
          "required": [
            "title",
            "duration"
          ],
          "properties": {
            "title": {
              "title": "Song title",
              "type": "string",
              "examples": [
                "Pork Soda",
                "Mama's Gun"
              ]
            },
            "duration": {
              "title": "Song duration",
              "type": "string",
              "examples": [
                "4:13",
                "3:52"
              ]
            }
          }
        }
      }
    }
  }
}

=== Asim-Tahir/rsc-vs-ssr-with-express/src/server/db/album/data.json
[
  {
    "id": "bjork-post",
    "artist": "Bj√∂rk",
    "title": "Post",
    "cover": "https://i.discogs.com/nKIGMO-FhgjIZAxpTKIx__vLsrg6XTEUEbeMXtgnJMs/rs:fit/g:sm/q:90/h:581/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMjQ4/MS0xMjMyMTQ2Nzgy/LmpwZWc.jpeg",
    "likes": 1,
    "songs": [
      {
        "title": "Army of Me",
        "duration": "4:00"
      },
      {
        "title": "Hyperballad",
        "duration": "5:21"
      },
      {
        "title": "The Modern Things",
        "duration": "4:00"
      },
      {
        "title": "It's Oh So Quiet",
        "duration": "4:00"
      },
      {
        "title": "Enjoy",
        "duration": "4:00"
      },
      {
        "title": "You've Been Flirting Again",
        "duration": "4:00"
      },
      {
        "title": "Isobel",
        "duration": "4:00"
      },
      {
        "title": "Possibly Maybe",
        "duration": "4:00"
      },
      {
        "title": "I Miss You",
        "duration": "4:00"
      },
      {
        "title": "Cover Me",
        "duration": "4:00"
      },
      {
        "title": "Headphones",
        "duration": "4:00"
      }
    ]
  },
  {
    "id": "glass-animals-how-to-be",
    "artist": "Glass Animals",
    "title": "How To Be A Human Being",
    "cover": "https://i.discogs.com/H-kC9IIS7dglokcAXmfrRHji0roeA3SMxrNFr9MtBzQ/rs:fit/g:sm/q:90/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg5NTM0/NzAtMTQ3MjE0NTUx/My03NjA2LmpwZWc.jpeg",
    "likes": 10,
    "songs": [
      {
        "title": "Life Itself",
        "duration": "4:41"
      },
      {
        "title": "Youth",
        "duration": "3:50"
      },
      {
        "title": "Season 2 Episode 3",
        "duration": "3:52"
      },
      {
        "title": "Pork Soda",
        "duration": "4:13"
      },
      {
        "title": "Mama's Gun",
        "duration": "3:52"
      },
      {
        "title": "Cane Shuga",
        "duration": "3:52"
      },
      {
        "title": "[Premade Sandwiches]",
        "duration": "0:36"
      },
      {
        "title": "The Other Side Of Paradise",
        "duration": "3:52"
      },
      {
        "title": "Take A Slice",
        "duration": "3:52"
      },
      {
        "title": "Poplar St",
        "duration": "3:52"
      },
      {
        "title": "Agnes",
        "duration": "3:52"
      }
    ]
  },
  {
    "id": "lady-gaga-the-fame",
    "artist": "Lady Gaga",
    "title": "The Fame",
    "cover": "https://i.discogs.com/0MgbgSVEqOrRtLwARinYwVPQHVqIq-pR0csL19pdmTg/rs:fit/g:sm/q:90/h:396/w:400/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MzI5/OTEtMTIxOTI4Njg0/MS5qcGVn.jpeg",
    "likes": 5,
    "songs": [
      {
        "title": "Just Dance",
        "duration": "4:01"
      },
      {
        "title": "LoveGame",
        "duration": "3:48"
      },
      {
        "title": "Paparazzi",
        "duration": "3:48"
      },
      {
        "title": "Poker Face",
        "duration": "3:58"
      },
      {
        "title": "Eh, Eh (Nothing Else I Can Say)",
        "duration": "3:47"
      },
      {
        "title": "Beautiful, Dirty, Rich",
        "duration": "3:47"
      },
      {
        "title": "The Fame",
        "duration": "3:47"
      },
      {
        "title": "Money Honey",
        "duration": "3:47"
      },
      {
        "title": "Starstruck",
        "duration": "3:47"
      },
      {
        "title": "Boys Boys Boys",
        "duration": "3:47"
      },
      {
        "title": "Paper Gangsta",
        "duration": "3:47"
      },
      {
        "title": "Brown Eyes",
        "duration": "3:47"
      },
      {
        "title": "I Like It Rough",
        "duration": "3:47"
      },
      {
        "title": "Summerboy",
        "duration": "3:47"
      },
      {
        "title": "Disco Heaven",
        "duration": "3:47"
      }
    ]
  }
]
